### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by valancej** [valancej/maven-demo#1]
```
details:
  msg: Reality is merely an illusion, albeit a very persistent one - Albert Einstein
id: ad8d692f7e304751837ca43451a406a0
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-api:8668
  hostid: anchore-anchore-engine-api-74cc4897c8-gj248
  request_id: null
  servicename: notifications
timestamp: '2022-03-07T23:51:57.826431'
type: system.test.random_wisdom
```
